### ISSUE TITLE
Rating must be between 0 to 10

### ISSUE THREAD

**Issue by ralphee** [Mythic82/Plex-Rating-Sync#1]
test run worked without any issues. Once I set the TEST_MODE variable to false i receive the following error:

`Traceback (most recent call last):
  File "/home/ralphe/Repo/Plex-Rating-Sync-default/Syncplexrating.py", line 249, in <module>
    process_flac(track, host_path)
  File "/home/ralphe/Repo/Plex-Rating-Sync-default/Syncplexrating.py", line 214, in process_flac
    track.rate(plex_rating)
  File "/usr/lib/python3.12/site-packages/plexapi/mixins.py", line 345, in rate
    raise BadRequest('Rating must be between 0 to 10.')
plexapi.exceptions.BadRequest: Rating must be between 0 to 10.`

**Comment by alienmare** [comment]
same issue also I found if flac with no rating it will give error ValueError: could not convert string to float: 'Clean'

**Comment by Mythic82** [comment]
Ok. Yes it was made to work with my ratings from jriver media player. So it
might have trouble if the ratings is not having the correct tags. I might
fix that, but will probably take a while before i get the time.
